packages:
  - '.'
overrides:
  minimatch@<4.0.0: 3.1.5
  flatted: '>=3.4.0'
  dompurify: '>=3.3.2'
onlyBuiltDependencies:
    - '@swc/core'
    - esbuild
allowBuilds:
  '@swc/core': true
  esbuild: true
